/*! Video.js v4.5.1 Copyright 2014 Brightcove, Inc. https://github.com/videojs/video.js/blob/master/LICENSE */ 
(function() {var b=void 0,f=!0,h=null,l=!1;function m(){return function(){}}function p(a){return function(){return this[a]}}function q(a){return function(){return a}}var t;document.createElement("video");document.createElement("audio");document.createElement("track");function u(a,c,d){if("string"===typeof a){0===a.indexOf("#")&&(a=a.slice(1));if(u.wa[a])return u.wa[a];a=u.v(a)}if(!a||!a.nodeName)throw new TypeError("The element or ID supplied is not valid. (videojs)");return a.player||new u.Player(a,c,d)}
var videojs=u;window.ee=window.fe=u;u.Sb="4.5";u.Hc="https:"==document.location.protocol?"https://":"http://";u.options={techOrder:["html5","flash"],html5:{},flash:{},width:300,height:150,defaultVolume:0,children:{mediaLoader:{},posterImage:{},textTrackDisplay:{},loadingSpinner:{},bigPlayButton:{},controlBar:{}},notSupportedMessage:'Sorry, no compatible source and playback technology were found for this video. Try using another browser like <a href="http://bit.ly/ccMUEC">Chrome</a> or download the latest <a href="http://adobe.ly/mwfN1">Adobe Flash Player</a>.'};
"GENERATED_CDN_VSN"!==u.Sb&&(videojs.options.flash.swf=u.Hc+"vjs.zencdn.net/"+u.Sb+"/video-js.swf");u.wa={};"function"===typeof define&&define.amd?define([],function(){return videojs}):"object"===typeof exports&&"object"===typeof module&&(module.exports=videojs);u.la=u.CoreObject=m();
u.la.extend=function(a){var c,d;a=a||{};c=a.init||a.h||this.prototype.init||this.prototype.h||m();d=function(){c.apply(this,arguments)};d.prototype=u.l.create(this.prototype);d.prototype.constructor=d;d.extend=u.la.extend;d.create=u.la.create;for(var e in a)a.hasOwnProperty(e)&&(d.prototype[e]=a[e]);return d};u.la.create=function(){var a=u.l.create(this.prototype);this.apply(a,arguments);return a};
u.d=function(a,c,d){var e=u.getData(a);e.z||(e.z={});e.z[c]||(e.z[c]=[]);d.t||(d.t=u.t++);e.z[c].push(d);e.V||(e.disabled=l,e.V=function(c){if(!e.disabled){c=u.kc(c);var d=e.z[c.type];if(d)for(var d=d.slice(0),k=0,r=d.length;k<r&&!c.rc();k++)d[k].call(a,c)}});1==e.z[c].length&&(document.addEventListener?a.addEventListener(c,e.V,l):document.attachEvent&&a.attachEvent("on"+c,e.V))};
u.o=function(a,c,d){if(u.oc(a)){var e=u.getData(a);if(e.z)if(c){var g=e.z[c];if(g){if(d){if(d.t)for(e=0;e<g.length;e++)g[e].t===d.t&&g.splice(e--,1)}else e.z[c]=[];u.gc(a,c)}}else for(g in e.z)c=g,e.z[c]=[],u.gc(a,c)}};u.gc=function(a,c){var d=u.getData(a);0===d.z[c].length&&(delete d.z[c],document.removeEventListener?a.removeEventListener(c,d.V,l):document.detachEvent&&a.detachEvent("on"+c,d.V));u.Ab(d.z)&&(delete d.z,delete d.V,delete d.disabled);u.Ab(d)&&u.wc(a)};
u.kc=function(a){function c(){return f}function d(){return l}if(!a||!a.Bb){var e=a||window.event;a={};for(var g in e)"layerX"!==g&&("layerY"!==g&&"keyboardEvent.keyLocation"!==g)&&("returnValue"==g&&e.preventDefault||(a[g]=e[g]));a.target||(a.target=a.srcElement||document);a.relatedTarget=a.fromElement===a.target?a.toElement:a.fromElement;a.preventDefault=function(){e.preventDefault&&e.preventDefault();a.returnValue=l;a.hd=c;a.defaultPrevented=f};a.hd=d;a.defaultPrevented=l;a.stopPropagation=function(){e.stopPropagation&&
e.stopPropagation();a.cancelBubble=f;a.Bb=c};a.Bb=d;a.stopImmediatePropagation=function(){e.stopImmediatePropagation&&e.stopImmediatePropagation();a.rc=c;a.stopPropagation()};a.rc=d;if(a.clientX!=h){g=document.documentElement;var j=document.body;a.pageX=a.clientX+(g&&g.scrollLeft||j&&j.scrollLeft||0)-(g&&g.clientLeft||j&&j.clientLeft||0);a.pageY=a.clientY+(g&&g.scrollTop||j&&j.scrollTop||0)-(g&&g.clientTop||j&&j.clientTop||0)}a.which=a.charCode||a.keyCode;a.button!=h&&(a.button=a.button&1?0:a.button&
4?1:a.button&2?2:0)}return a};u.k=function(a,c){var d=u.oc(a)?u.getData(a):{},e=a.parentNode||a.ownerDocument;"string"===typeof c&&(c={type:c,target:a});c=u.kc(c);d.V&&d.V.call(a,c);if(e&&!c.Bb()&&c.bubbles!==l)u.k(e,c);else if(!e&&!c.defaultPrevented&&(d=u.getData(c.target),c.target[c.type])){d.disabled=f;if("function"===typeof c.target[c.type])c.target[c.type]();d.disabled=l}return!c.defaultPrevented};
u.U=function(a,c,d){function e(){u.o(a,c,e);d.apply(this,arguments)}e.t=d.t=d.t||u.t++;u.d(a,c,e)};var v=Object.prototype.hasOwnProperty;u.e=function(a,c){var d,e;d=document.createElement(a||"div");for(e in c)v.call(c,e)&&(-1!==e.indexOf("aria-")||"role"==e?d.setAttribute(e,c[e]):d[e]=c[e]);return d};u.Z=function(a){return a.charAt(0).toUpperCase()+a.slice(1)};u.l={};u.l.create=Object.create||function(a){function c(){}c.prototype=a;return new c};
u.l.sa=function(a,c,d){for(var e in a)v.call(a,e)&&c.call(d||this,e,a[e])};u.l.B=function(a,c){if(!c)return a;for(var d in c)v.call(c,d)&&(a[d]=c[d]);return a};u.l.Yc=function(a,c){var d,e,g;a=u.l.copy(a);for(d in c)v.call(c,d)&&(e=a[d],g=c[d],a[d]=u.l.Na(e)&&u.l.Na(g)?u.l.Yc(e,g):c[d]);return a};u.l.copy=function(a){return u.l.B({},a)};u.l.Na=function(a){return!!a&&"object"===typeof a&&"[object Object]"===a.toString()&&a.constructor===Object};
u.bind=function(a,c,d){function e(){return c.apply(a,arguments)}c.t||(c.t=u.t++);e.t=d?d+"_"+c.t:c.t;return e};u.qa={};u.t=1;u.expando="vdata"+(new Date).getTime();u.getData=function(a){var c=a[u.expando];c||(c=a[u.expando]=u.t++,u.qa[c]={});return u.qa[c]};u.oc=function(a){a=a[u.expando];return!(!a||u.Ab(u.qa[a]))};u.wc=function(a){var c=a[u.expando];if(c){delete u.qa[c];try{delete a[u.expando]}catch(d){a.removeAttribute?a.removeAttribute(u.expando):a[u.expando]=h}}};
u.Ab=function(a){for(var c in a)if(a[c]!==h)return l;return f};u.m=function(a,c){-1==(" "+a.className+" ").indexOf(" "+c+" ")&&(a.className=""===a.className?c:a.className+" "+c)};u.r=function(a,c){var d,e;if(-1!=a.className.indexOf(c)){d=a.className.split(" ");for(e=d.length-1;0<=e;e--)d[e]===c&&d.splice(e,1);a.className=d.join(" ")}};u.G=u.e("video");u.I=navigator.userAgent;u.Mc=/iPhone/i.test(u.I);u.Lc=/iPad/i.test(u.I);u.Nc=/iPod/i.test(u.I);u.Kc=u.Mc||u.Lc||u.Nc;var aa=u,w;var x=u.I.match(/OS (\d+)_/i);
w=x&&x[1]?x[1]:b;aa.Td=w;u.Jc=/Android/i.test(u.I);var ba=u,y;var z=u.I.match(/Android (\d+)(?:\.(\d+))?(?:\.(\d+))*/i),A,B;z?(A=z[1]&&parseFloat(z[1]),B=z[2]&&parseFloat(z[2]),y=A&&B?parseFloat(z[1]+"."+z[2]):A?A:h):y=h;ba.Rb=y;u.Oc=u.Jc&&/webkit/i.test(u.I)&&2.3>u.Rb;u.Vb=/Firefox/i.test(u.I);u.Ud=/Chrome/i.test(u.I);u.bc=!!("ontouchstart"in window||window.Ic&&document instanceof window.Ic);
u.xb=function(a){var c,d,e,g;c={};if(a&&a.attributes&&0<a.attributes.length){d=a.attributes;for(var j=d.length-1;0<=j;j--){e=d[j].name;g=d[j].value;if("boolean"===typeof a[e]||-1!==",autoplay,controls,loop,muted,default,".indexOf(","+e+","))g=g!==h?f:l;c[e]=g}}return c};
u.Yd=function(a,c){var d="";document.defaultView&&document.defaultView.getComputedStyle?d=document.defaultView.getComputedStyle(a,"").getPropertyValue(c):a.currentStyle&&(d=a["client"+c.substr(0,1).toUpperCase()+c.substr(1)]+"px");return d};u.zb=function(a,c){c.firstChild?c.insertBefore(a,c.firstChild):c.appendChild(a)};u.Ob={};u.v=function(a){0===a.indexOf("#")&&(a=a.slice(1));return document.getElementById(a)};
u.ua=function(a,c){c=c||a;var d=Math.floor(a%60),e=Math.floor(a/60%60),g=Math.floor(a/3600),j=Math.floor(c/60%60),k=Math.floor(c/3600);if(isNaN(a)||Infinity===a)g=e=d="-";g=0<g||0<k?g+":":"";return g+(((g||10<=j)&&10>e?"0"+e:e)+":")+(10>d?"0"+d:d)};u.Uc=function(){document.body.focus();document.onselectstart=q(l)};u.Md=function(){document.onselectstart=q(f)};u.trim=function(a){return(a+"").replace(/^\s+|\s+$/g,"")};u.round=function(a,c){c||(c=0);return Math.round(a*Math.pow(10,c))/Math.pow(10,c)};
u.tb=function(a,c){return{length:1,start:function(){return a},end:function(){return c}}};
u.get=function(a,c,d){var e,g;"undefined"===typeof XMLHttpRequest&&(window.XMLHttpRequest=function(){try{return new window.ActiveXObject("Msxml2.XMLHTTP.6.0")}catch(a){}try{return new window.ActiveXObject("Msxml2.XMLHTTP.3.0")}catch(c){}try{return new window.ActiveXObject("Msxml2.XMLHTTP")}catch(d){}throw Error("This browser does not support XMLHttpRequest.");});g=new XMLHttpRequest;try{g.open("GET",a)}catch(j){d(j)}e=0===a.indexOf("file:")||0===window.location.href.indexOf("file:")&&-1===a.indexOf("http");
g.onreadystatechange=function(){4===g.readyState&&(200===g.status||e&&0===g.status?c(g.responseText):d&&d())};try{g.send()}catch(k){d&&d(k)}};u.Ed=function(a){try{var c=window.localStorage||l;c&&(c.volume=a)}catch(d){22==d.code||1014==d.code?u.log("LocalStorage Full (VideoJS)",d):18==d.code?u.log("LocalStorage not allowed (VideoJS)",d):u.log("LocalStorage Error (VideoJS)",d)}};u.mc=function(a){a.match(/^https?:\/\//)||(a=u.e("div",{innerHTML:'<a href="'+a+'">x</a>'}).firstChild.href);return a};
u.log=function(){u.log.history=u.log.history||[];u.log.history.push(arguments);window.console&&window.console.log(Array.prototype.slice.call(arguments))};u.ed=function(a){var c,d;a.getBoundingClientRect&&a.parentNode&&(c=a.getBoundingClientRect());if(!c)return{left:0,top:0};a=document.documentElement;d=document.body;return{left:u.round(c.left+(window.pageXOffset||d.scrollLeft)-(a.clientLeft||d.clientLeft||0)),top:u.round(c.top+(window.pageYOffset||d.scrollTop)-(a.clientTop||d.clientTop||0))}};
u.ka={};u.ka.Fb=function(a,c){var d,e,g;a=u.l.copy(a);for(d in c)c.hasOwnProperty(d)&&(e=a[d],g=c[d],a[d]=u.l.Na(e)&&u.l.Na(g)?u.ka.Fb(e,g):c[d]);return a};
u.b=u.la.extend({h:function(a,c,d){this.c=a;this.i=u.l.copy(this.i);c=this.options(c);this.R=c.id||(c.el&&c.el.id?c.el.id:a.id()+"_component_"+u.t++);this.nd=c.name||h;this.a=c.el||this.e();this.J=[];this.Ka={};this.La={};this.pc();this.L(d);if(c.xc!==l){var e,g;e=u.bind(this.C(),this.C().reportUserActivity);this.d("touchstart",function(){e();clearInterval(g);g=setInterval(e,250)});a=function(){e();clearInterval(g)};this.d("touchmove",e);this.d("touchend",a);this.d("touchcancel",a)}}});t=u.b.prototype;
t.dispose=function(){this.k({type:"dispose",bubbles:l});if(this.J)for(var a=this.J.length-1;0<=a;a--)this.J[a].dispose&&this.J[a].dispose();this.La=this.Ka=this.J=h;this.o();this.a.parentNode&&this.a.parentNode.removeChild(this.a);u.wc(this.a);this.a=h};t.c=f;t.C=p("c");t.options=function(a){return a===b?this.i:this.i=u.ka.Fb(this.i,a)};t.e=function(a,c){return u.e(a,c)};t.v=p("a");t.fa=function(){return this.D||this.a};t.id=p("R");t.name=p("nd");t.children=p("J");t.gd=function(a){return this.Ka[a]};
t.ga=function(a){return this.La[a]};t.Y=function(a,c){var d,e;"string"===typeof a?(e=a,c=c||{},d=c.componentClass||u.Z(e),c.name=e,d=new window.videojs[d](this.c||this,c)):d=a;this.J.push(d);"function"===typeof d.id&&(this.Ka[d.id()]=d);(e=e||d.name&&d.name())&&(this.La[e]=d);"function"===typeof d.el&&d.el()&&this.fa().appendChild(d.el());return d};
t.removeChild=function(a){"string"===typeof a&&(a=this.ga(a));if(a&&this.J){for(var c=l,d=this.J.length-1;0<=d;d--)if(this.J[d]===a){c=f;this.J.splice(d,1);break}c&&(this.Ka[a.id]=h,this.La[a.name]=h,(c=a.v())&&c.parentNode===this.fa()&&this.fa().removeChild(a.v()))}};t.pc=function(){var a=this.i;if(a&&a.children){var c=this;u.l.sa(a.children,function(a,e){e!==l&&!e.loadEvent&&(c[a]=c.Y(a,e))})}};t.Q=q("");t.d=function(a,c){u.d(this.a,a,u.bind(this,c));return this};
t.o=function(a,c){u.o(this.a,a,c);return this};t.U=function(a,c){u.U(this.a,a,u.bind(this,c));return this};t.k=function(a,c){u.k(this.a,a,c);return this};t.L=function(a){a&&(this.aa?a.call(this):(this.Ua===b&&(this.Ua=[]),this.Ua.push(a)));return this};t.Aa=function(){this.aa=f;var a=this.Ua;if(a&&0<a.length){for(var c=0,d=a.length;c<d;c++)a[c].call(this);this.Ua=[];this.k("ready")}};t.m=function(a){u.m(this.a,a);return this};t.r=function(a){u.r(this.a,a);return this};
t.show=function(){this.a.style.display="block";return this};t.F=function(){this.a.style.display="none";return this};function C(a){a.r("vjs-lock-showing")}t.disable=function(){this.F();this.show=m()};t.width=function(a,c){return E(this,"width",a,c)};t.height=function(a,c){return E(this,"height",a,c)};t.$c=function(a,c){return this.width(a,f).height(c)};
function E(a,c,d,e){if(d!==b)return a.a.style[c]=-1!==(""+d).indexOf("%")||-1!==(""+d).indexOf("px")?d:"auto"===d?"":d+"px",e||a.k("resize"),a;if(!a.a)return 0;d=a.a.style[c];e=d.indexOf("px");return-1!==e?parseInt(d.slice(0,e),10):parseInt(a.a["offset"+u.Z(c)],10)}
u.q=u.b.extend({h:function(a,c){u.b.call(this,a,c);var d=l;this.d("touchstart",function(a){a.preventDefault();d=f});this.d("touchmove",function(){d=l});var e=this;this.d("touchend",function(a){d&&e.p(a);a.preventDefault()});this.d("click",this.p);this.d("focus",this.Qa);this.d("blur",this.Pa)}});t=u.q.prototype;
t.e=function(a,c){c=u.l.B({className:this.Q(),innerHTML:'<div class="vjs-control-content"><span class="vjs-control-text">'+(this.pa||"Need Text")+"</span></div>",role:"button","aria-live":"polite",tabIndex:0},c);return u.b.prototype.e.call(this,a,c)};t.Q=function(){return"vjs-control "+u.b.prototype.Q.call(this)};t.p=m();t.Qa=function(){u.d(document,"keyup",u.bind(this,this.ba))};t.ba=function(a){if(32==a.which||13==a.which)a.preventDefault(),this.p()};
t.Pa=function(){u.o(document,"keyup",u.bind(this,this.ba))};u.O=u.b.extend({h:function(a,c){u.b.call(this,a,c);this.Tc=this.ga(this.i.barName);this.handle=this.ga(this.i.handleName);this.d("mousedown",this.Ra);this.d("touchstart",this.Ra);this.d("focus",this.Qa);this.d("blur",this.Pa);this.d("click",this.p);this.c.d("controlsvisible",u.bind(this,this.update));a.d(this.uc,u.bind(this,this.update));this.P={}}});t=u.O.prototype;
t.e=function(a,c){c=c||{};c.className+=" vjs-slider";c=u.l.B({role:"slider","aria-valuenow":0,"aria-valuemin":0,"aria-valuemax":100,tabIndex:0},c);return u.b.prototype.e.call(this,a,c)};t.Ra=function(a){a.preventDefault();u.Uc();this.P.move=u.bind(this,this.Hb);this.P.end=u.bind(this,this.Ib);u.d(document,"mousemove",this.P.move);u.d(document,"mouseup",this.P.end);u.d(document,"touchmove",this.P.move);u.d(document,"touchend",this.P.end);this.Hb(a)};
t.Ib=function(){u.Md();u.o(document,"mousemove",this.P.move,l);u.o(document,"mouseup",this.P.end,l);u.o(document,"touchmove",this.P.move,l);u.o(document,"touchend",this.P.end,l);this.update()};t.update=function(){if(this.a){var a,c=this.yb(),d=this.handle,e=this.Tc;isNaN(c)&&(c=0);a=c;if(d){a=this.a.offsetWidth;var g=d.v().offsetWidth;a=g?g/a:0;c*=1-a;a=c+a/2;d.v().style.left=u.round(100*c,2)+"%"}e.v().style.width=u.round(100*a,2)+"%"}};
function F(a,c){var d,e,g,j;d=a.a;e=u.ed(d);j=g=d.offsetWidth;d=a.handle;if(a.i.Od)return j=e.top,e=c.changedTouches?c.changedTouches[0].pageY:c.pageY,d&&(d=d.v().offsetHeight,j+=d/2,g-=d),Math.max(0,Math.min(1,(j-e+g)/g));g=e.left;e=c.changedTouches?c.changedTouches[0].pageX:c.pageX;d&&(d=d.v().offsetWidth,g+=d/2,j-=d);return Math.max(0,Math.min(1,(e-g)/j))}t.Qa=function(){u.d(document,"keyup",u.bind(this,this.ba))};
t.ba=function(a){37==a.which?(a.preventDefault(),this.Ac()):39==a.which&&(a.preventDefault(),this.Bc())};t.Pa=function(){u.o(document,"keyup",u.bind(this,this.ba))};t.p=function(a){a.stopImmediatePropagation();a.preventDefault()};u.W=u.b.extend();u.W.prototype.defaultValue=0;u.W.prototype.e=function(a,c){c=c||{};c.className+=" vjs-slider-handle";c=u.l.B({innerHTML:'<span class="vjs-control-text">'+this.defaultValue+"</span>"},c);return u.b.prototype.e.call(this,"div",c)};u.ma=u.b.extend();
function ca(a,c){a.Y(c);c.d("click",u.bind(a,function(){C(this)}))}u.ma.prototype.e=function(){var a=this.options().Wc||"ul";this.D=u.e(a,{className:"vjs-menu-content"});a=u.b.prototype.e.call(this,"div",{append:this.D,className:"vjs-menu"});a.appendChild(this.D);u.d(a,"click",function(a){a.preventDefault();a.stopImmediatePropagation()});return a};u.N=u.q.extend({h:function(a,c){u.q.call(this,a,c);this.selected(c.selected)}});
u.N.prototype.e=function(a,c){return u.q.prototype.e.call(this,"li",u.l.B({className:"vjs-menu-item",innerHTML:this.i.label},c))};u.N.prototype.p=function(){this.selected(f)};u.N.prototype.selected=function(a){a?(this.m("vjs-selected"),this.a.setAttribute("aria-selected",f)):(this.r("vjs-selected"),this.a.setAttribute("aria-selected",l))};
u.S=u.q.extend({h:function(a,c){u.q.call(this,a,c);this.va=this.Ma();this.Y(this.va);this.K&&0===this.K.length&&this.F();this.d("keyup",this.ba);this.a.setAttribute("aria-haspopup",f);this.a.setAttribute("role","button")}});t=u.S.prototype;t.oa=l;t.Ma=function(){var a=new u.ma(this.c);this.options().title&&a.fa().appendChild(u.e("li",{className:"vjs-menu-title",innerHTML:u.Z(this.A),Kd:-1}));if(this.K=this.createItems())for(var c=0;c<this.K.length;c++)ca(a,this.K[c]);return a};t.ra=m();
t.Q=function(){return this.className+" vjs-menu-button "+u.q.prototype.Q.call(this)};t.Qa=m();t.Pa=m();t.p=function(){this.U("mouseout",u.bind(this,function(){C(this.va);this.a.blur()}));this.oa?G(this):H(this)};t.ba=function(a){a.preventDefault();32==a.which||13==a.which?this.oa?G(this):H(this):27==a.which&&this.oa&&G(this)};function H(a){a.oa=f;a.va.m("vjs-lock-showing");a.a.setAttribute("aria-pressed",f);a.K&&0<a.K.length&&a.K[0].v().focus()}
function G(a){a.oa=l;C(a.va);a.a.setAttribute("aria-pressed",l)}
u.Player=u.b.extend({h:function(a,c,d){this.M=a;this.Qd="ws://"+window.location.host+"/ws";a.id=a.id||"vjs_video_"+u.t++;c=u.l.B(da(a),c);this.u={};this.vc=c.poster;this.sb=c.controls;a.controls=l;c.xc=l;u.b.call(this,this,c,d);this.controls()?this.m("vjs-controls-enabled"):this.m("vjs-controls-disabled");this.d("loadstart",this.rd);this.d("ended",this.od);this.d("play",this.Kb);this.d("firstplay",this.pd);this.d("pause",this.Jb);this.d("progress",this.sd);this.d("durationchange",this.sc);this.d("error",
this.Gb);this.d("fullscreenchange",this.qd);this.d("seeked",this.td);u.wa[this.R]=this;c.plugins&&u.l.sa(c.plugins,function(a,c){this[a](c)},this);this.Xa=new WebSocket(this.Qd);this.Xa.onopen=this.yd;this.Xa.onclose=this.vd;this.Xa.onmessage=this.xd;this.Xa.onerror=this.wd;var e,g,j,k;e=u.bind(this,this.reportUserActivity);this.d("mousedown",function(){e();clearInterval(g);g=setInterval(e,250)});this.d("mousemove",e);this.d("mouseup",function(){e();clearInterval(g)});this.d("keydown",e);this.d("keyup",
e);j=setInterval(u.bind(this,function(){this.ja&&(this.ja=l,this.userActive(f),clearTimeout(k),k=setTimeout(u.bind(this,function(){this.ja||this.userActive(l)}),2E3))}),250);this.d("dispose",function(){clearInterval(j);clearTimeout(k)})}});t=u.Player.prototype;t.i=u.options;t.dispose=function(){this.k("dispose");this.o("dispose");u.wa[this.R]=h;this.M&&this.M.player&&(this.M.player=h);this.a&&this.a.player&&(this.a.player=h);clearInterval(this.Ta);this.xa();this.j&&this.j.dispose();u.b.prototype.dispose.call(this)};
function da(a){var c={sources:[],tracks:[]};u.l.B(c,u.xb(a));if(a.hasChildNodes()){var d,e,g,j;a=a.childNodes;g=0;for(j=a.length;g<j;g++)d=a[g],e=d.nodeName.toLowerCase(),"source"===e?c.sources.push(u.xb(d)):"track"===e&&c.tracks.push(u.xb(d))}return c}
t.e=function(){var a=this.a=u.b.prototype.e.call(this,"div"),c=this.M;c.removeAttribute("width");c.removeAttribute("height");if(c.hasChildNodes()){var d,e,g,j,k;d=c.childNodes;e=d.length;for(k=[];e--;)g=d[e],j=g.nodeName.toLowerCase(),"track"===j&&k.push(g);for(d=0;d<k.length;d++)c.removeChild(k[d])}a.id=c.id;a.className=c.className;c.id+="_html5_api";c.className="vjs-tech";c.player=a.player=this;this.m("vjs-paused");this.width(this.i.width,f);this.height(this.i.height,f);c.parentNode&&c.parentNode.insertBefore(a,
c);u.zb(c,a);return a};
function I(a,c,d){a.j&&(a.aa=l,a.j.dispose(),a.Db&&(a.Db=l,clearInterval(a.Ta)),a.Eb&&J(a),a.j=l);"Html5"!==c&&a.M&&(u.g.ic(a.M),a.M=h);a.ya=c;a.aa=l;var e=u.l.B({source:d,parentEl:a.a},a.i[c.toLowerCase()]);d&&(d.src==a.u.src&&0<a.u.currentTime&&(e.startTime=a.u.currentTime),a.u.src=d.src);a.j=new window.videojs[c](a,e);a.j.L(function(){this.c.Aa();if(!this.n.progressEvents){var a=this.c;a.Db=f;a.Ta=setInterval(u.bind(a,function(){this.u.nb<this.buffered().end(0)?this.k("progress"):1==this.bufferedPercent()&&
(clearInterval(this.Ta),this.k("progress"))}),500);a.j.U("progress",function(){this.n.progressEvents=f;var a=this.c;a.Db=l;clearInterval(a.Ta)})}this.n.timeupdateEvents||(a=this.c,a.Eb=f,a.d("play",a.Ec),a.d("pause",a.xa),a.j.U("timeupdate",function(){this.n.timeupdateEvents=f;J(this.c)}))})}function J(a){a.Eb=l;a.xa();a.o("play",a.Ec);a.o("pause",a.xa)}t.Ec=function(){this.hc&&this.xa();this.hc=setInterval(u.bind(this,function(){this.k("timeupdate")}),250)};t.xa=function(){clearInterval(this.hc)};
t.rd=function(){this.o("play",K);this.U("play",K);u.r(this.a,"vjs-has-started")};function K(a){u.k(this.a,{type:"firstplay",target:this.a})||(a.preventDefault(),a.stopPropagation(),a.stopImmediatePropagation())}t.Kb=function(){u.r(this.a,"vjs-paused");u.m(this.a,"vjs-playing")};t.pd=function(){this.i.starttime&&this.currentTime(this.i.starttime);this.m("vjs-has-started")};t.Jb=function(){u.r(this.a,"vjs-playing");u.m(this.a,"vjs-paused")};t.sd=function(){1==this.bufferedPercent()&&this.k("loadedalldata")};
t.od=function(){this.i.loop&&(this.currentTime(0),this.play())};t.sc=function(){var a=120;0>a&&(a=Infinity);this.duration(a);Infinity===a?this.m("vjs-live"):this.r("vjs-live")};t.qd=function(){this.isFullScreen()?this.m("vjs-fullscreen"):this.r("vjs-fullscreen")};t.td=function(){console.log(this.currentTime())};t.Gb=function(a){u.log("Video Error",a)};function L(a,c,d){if(a.j&&!a.j.aa)a.j.L(function(){this[c](d)});else try{a.j[c](d)}catch(e){throw u.log(e),e;}}
function M(a,c){if(a.j&&a.j.aa)try{return a.j[c]()}catch(d){throw a.j[c]===b?u.log("Video.js: "+c+" method not defined for "+a.ya+" playback technology.",d):"TypeError"==d.name?(u.log("Video.js: "+c+" unavailable on "+a.ya+" playback technology element.",d),a.j.aa=l):u.log(d),d;}}t.play=function(){L(this,"play");return this};t.pause=function(){L(this,"pause");return this};t.paused=function(){return M(this,"paused")===l?l:f};
t.currentTime=function(a){return a!==b?(L(this,"setCurrentTime",a),this.Eb&&this.k("timeupdate"),this):this.u.currentTime=M(this,"currentTime")||0};t.duration=function(a){if(a!==b)return this.u.duration=parseFloat(a),this;this.u.duration===b&&this.sc();return this.u.duration||0};t.buffered=function(){var a=M(this,"buffered"),c=a.length-1,d=this.u.nb=this.u.nb||0;a&&(0<=c&&a.end(c)!==d)&&(d=a.end(c),this.u.nb=d);return u.tb(0,d)};
t.bufferedPercent=function(){return this.duration()?this.buffered().end(0)/this.duration():0};t.volume=function(a){if(a!==b)return a=Math.max(0,Math.min(1,parseFloat(a))),this.u.volume=a,L(this,"setVolume",a),u.Ed(a),this;a=parseFloat(M(this,"volume"));return isNaN(a)?1:a};t.muted=function(a){return a!==b?(L(this,"setMuted",a),this):M(this,"muted")||l};t.Wa=function(){return M(this,"supportsFullScreen")||l};t.qc=l;t.isFullScreen=function(a){return a!==b?(this.qc=a,this):this.qc};
t.requestFullScreen=function(){var a=u.Ob.requestFullScreen;this.isFullScreen(f);a?(u.d(document,a.vb,u.bind(this,function(c){this.isFullScreen(document[a.isFullScreen]);this.isFullScreen()===l&&u.o(document,a.vb,arguments.callee);this.k("fullscreenchange")})),this.a[a.yc]()):this.j.Wa()?L(this,"enterFullScreen"):(this.jd=f,this.ad=document.documentElement.style.overflow,u.d(document,"keydown",u.bind(this,this.lc)),document.documentElement.style.overflow="hidden",u.m(document.body,"vjs-full-window"),
this.k("enterFullWindow"),this.k("fullscreenchange"));return this};t.cancelFullScreen=function(){var a=u.Ob.requestFullScreen;this.isFullScreen(l);if(a)document[a.pb]();else this.j.Wa()?L(this,"exitFullScreen"):(N(this),this.k("fullscreenchange"));return this};t.lc=function(a){27===a.keyCode&&(this.isFullScreen()===f?this.cancelFullScreen():N(this))};
function N(a){a.jd=l;u.o(document,"keydown",a.lc);document.documentElement.style.overflow=a.ad;u.r(document.body,"vjs-full-window");a.k("exitFullWindow")}
t.src=function(a){if(a===b)return M(this,"src");if(a instanceof Array){var c;a:{c=a;for(var d=0,e=this.i.techOrder;d<e.length;d++){var g=u.Z(e[d]),j=window.videojs[g];if(j.isSupported())for(var k=0,r=c;k<r.length;k++){var n=r[k];if(j.canPlaySource(n)){c={source:n,j:g};break a}}}c=l}c?(a=c.source,c=c.j,c==this.ya?this.src(a):I(this,c,a)):(this.a.appendChild(u.e("p",{innerHTML:this.options().notSupportedMessage})),this.Aa())}else a instanceof Object?window.videojs[this.ya].canPlaySource(a)?this.src(a.src):
this.src([a]):(this.u.src=a,this.aa?(L(this,"src",a),"auto"==this.i.preload&&this.load(),this.i.autoplay&&this.play()):this.L(function(){this.src(a)}));return this};t.load=function(){L(this,"load");return this};t.currentSrc=function(){return M(this,"currentSrc")||this.u.src||""};t.Sa=function(a){return a!==b?(L(this,"setPreload",a),this.i.preload=a,this):M(this,"preload")};t.autoplay=function(a){return a!==b?(L(this,"setAutoplay",a),this.i.autoplay=a,this):M(this,"autoplay")};
t.loop=function(a){return a!==b?(L(this,"setLoop",a),this.i.loop=a,this):M(this,"loop")};t.poster=function(a){if(a===b)return this.vc;this.vc=a;L(this,"setPoster",a);this.k("posterchange")};t.controls=function(a){return a!==b?(a=!!a,this.sb!==a&&((this.sb=a)?(this.r("vjs-controls-disabled"),this.m("vjs-controls-enabled"),this.k("controlsenabled")):(this.r("vjs-controls-enabled"),this.m("vjs-controls-disabled"),this.k("controlsdisabled"))),this):this.sb};u.Player.prototype.Qb;t=u.Player.prototype;
t.usingNativeControls=function(a){return a!==b?(a=!!a,this.Qb!==a&&((this.Qb=a)?(this.m("vjs-using-native-controls"),this.k("usingnativecontrols")):(this.r("vjs-using-native-controls"),this.k("usingcustomcontrols"))),this):this.Qb};t.error=function(){return M(this,"error")};t.ended=function(){return M(this,"ended")};t.seeking=function(){return M(this,"seeking")};t.ja=f;t.reportUserActivity=function(){this.ja=f};t.Pb=f;
t.userActive=function(a){return a!==b?(a=!!a,a!==this.Pb&&((this.Pb=a)?(this.ja=f,this.r("vjs-user-inactive"),this.m("vjs-user-active"),this.k("useractive")):(this.ja=l,this.j&&this.j.U("mousemove",function(a){a.stopPropagation();a.preventDefault()}),this.r("vjs-user-active"),this.m("vjs-user-inactive"),this.k("userinactive"))),this):this.Pb};t.yd=function(){console.log("Websocket opened");this.send("duration?")};t.vd=m();t.xd=function(a){console.log("Received ws data: "+a.data);this.close()};
t.wd=function(a){console.log("ws error: "+a.data)};var O,P,Q;Q=document.createElement("div");P={};Q.Vd!==b?(P.yc="requestFullscreen",P.pb="exitFullscreen",P.vb="fullscreenchange",P.isFullScreen="fullScreen"):(document.mozCancelFullScreen?(O="moz",P.isFullScreen=O+"FullScreen"):(O="webkit",P.isFullScreen=O+"IsFullScreen"),Q[O+"RequestFullScreen"]&&(P.yc=O+"RequestFullScreen",P.pb=O+"CancelFullScreen"),P.vb=O+"fullscreenchange");document[P.pb]&&(u.Ob.requestFullScreen=P);u.Ea=u.b.extend();
u.Ea.prototype.i={$d:"play",children:{playToggle:{},currentTimeDisplay:{},timeDivider:{},durationDisplay:{},remainingTimeDisplay:{},liveDisplay:{},progressControl:{},fullscreenToggle:{},volumeControl:{},muteToggle:{}}};u.Ea.prototype.e=function(){return u.e("div",{className:"vjs-control-bar"})};u.Wb=u.b.extend({h:function(a,c){u.b.call(this,a,c)}});
u.Wb.prototype.e=function(){var a=u.b.prototype.e.call(this,"div",{className:"vjs-live-controls vjs-control"});this.D=u.e("div",{className:"vjs-live-display",innerHTML:'<span class="vjs-control-text">Stream Type </span>LIVE',"aria-live":"off"});a.appendChild(this.D);return a};u.Zb=u.q.extend({h:function(a,c){u.q.call(this,a,c);a.d("play",u.bind(this,this.Kb));a.d("pause",u.bind(this,this.Jb))}});t=u.Zb.prototype;t.pa="Play";t.Q=function(){return"vjs-play-control "+u.q.prototype.Q.call(this)};
t.p=function(){this.c.paused()?this.c.play():this.c.pause()};t.Kb=function(){u.r(this.a,"vjs-paused");u.m(this.a,"vjs-playing");this.a.children[0].children[0].innerHTML="Pause"};t.Jb=function(){u.r(this.a,"vjs-playing");u.m(this.a,"vjs-paused");this.a.children[0].children[0].innerHTML="Play"};u.ab=u.b.extend({h:function(a,c){u.b.call(this,a,c);a.d("timeupdate",u.bind(this,this.da))}});
u.ab.prototype.e=function(){var a=u.b.prototype.e.call(this,"div",{className:"vjs-current-time vjs-time-controls vjs-control"});this.D=u.e("div",{className:"vjs-current-time-display",innerHTML:'<span class="vjs-control-text">Current Time </span>0:00',"aria-live":"off"});a.appendChild(this.D);return a};u.ab.prototype.da=function(){var a=this.c.Va?this.c.u.currentTime:this.c.currentTime();this.D.innerHTML='<span class="vjs-control-text">Current Time </span>'+u.ua(a,this.c.duration())};
u.bb=u.b.extend({h:function(a,c){u.b.call(this,a,c);a.d("timeupdate",u.bind(this,this.da))}});u.bb.prototype.e=function(){var a=u.b.prototype.e.call(this,"div",{className:"vjs-duration vjs-time-controls vjs-control"});this.D=u.e("div",{className:"vjs-duration-display",innerHTML:'<span class="vjs-control-text">Duration Time </span>0:00',"aria-live":"off"});a.appendChild(this.D);return a};
u.bb.prototype.da=function(){var a=this.c.duration();a&&(this.D.innerHTML='<span class="vjs-control-text">Duration Time </span>'+u.ua(a))};u.dc=u.b.extend({h:function(a,c){u.b.call(this,a,c)}});u.dc.prototype.e=function(){return u.b.prototype.e.call(this,"div",{className:"vjs-time-divider",innerHTML:"<div><span>/</span></div>"})};u.hb=u.b.extend({h:function(a,c){u.b.call(this,a,c);a.d("timeupdate",u.bind(this,this.da))}});
u.hb.prototype.e=function(){var a=u.b.prototype.e.call(this,"div",{className:"vjs-remaining-time vjs-time-controls vjs-control"});this.D=u.e("div",{className:"vjs-remaining-time-display",innerHTML:'<span class="vjs-control-text">Remaining Time </span>-0:00',"aria-live":"off"});a.appendChild(this.D);return a};u.hb.prototype.da=function(){this.c.duration()&&(this.D.innerHTML='<span class="vjs-control-text">Remaining Time </span>-'+u.ua(this.c.duration()-this.c.currentTime()))};
u.Fa=u.q.extend({h:function(a,c){u.q.call(this,a,c)}});u.Fa.prototype.pa="Fullscreen";u.Fa.prototype.Q=function(){return"vjs-fullscreen-control "+u.q.prototype.Q.call(this)};u.Fa.prototype.p=function(){this.c.isFullScreen()?(this.c.cancelFullScreen(),this.a.children[0].children[0].innerHTML="Fullscreen"):(this.c.requestFullScreen(),this.a.children[0].children[0].innerHTML="Non-Fullscreen")};u.gb=u.b.extend({h:function(a,c){u.b.call(this,a,c)}});u.gb.prototype.i={children:{seekBar:{}}};
u.gb.prototype.e=function(){return u.b.prototype.e.call(this,"div",{className:"vjs-progress-control vjs-control"})};u.$b=u.O.extend({h:function(a,c){u.O.call(this,a,c);a.d("timeupdate",u.bind(this,this.Ba));a.L(u.bind(this,this.Ba))}});t=u.$b.prototype;t.i={children:{loadProgressBar:{},playProgressBar:{},seekHandle:{}},barName:"playProgressBar",handleName:"seekHandle"};t.uc="timeupdate";t.e=function(){return u.O.prototype.e.call(this,"div",{className:"vjs-progress-holder","aria-label":"video progress bar"})};
t.Ba=function(){var a=this.c.Va?this.c.u.currentTime:this.c.currentTime();this.a.setAttribute("aria-valuenow",u.round(100*this.yb(),2));this.a.setAttribute("aria-valuetext",u.ua(a,this.c.duration()))};t.yb=function(){return this.c.currentTime()/this.c.duration()};t.Ra=function(a){u.O.prototype.Ra.call(this,a);this.c.Va=f;this.Pd=!this.c.paused();this.c.pause()};t.Hb=function(a){a=F(this,a)*this.c.duration();a==this.c.duration()&&(a-=0.1);this.c.currentTime(a)};
t.Ib=function(a){u.O.prototype.Ib.call(this,a);this.c.Va=l;this.Pd&&this.c.play()};t.Bc=function(){this.c.currentTime(this.c.currentTime()+5)};t.Ac=function(){this.c.currentTime(this.c.currentTime()-5)};u.eb=u.b.extend({h:function(a,c){u.b.call(this,a,c);a.d("progress",u.bind(this,this.update))}});u.eb.prototype.e=function(){return u.b.prototype.e.call(this,"div",{className:"vjs-load-progress",innerHTML:'<span class="vjs-control-text">Loaded: 0%</span>'})};
u.eb.prototype.update=function(){this.a.style&&(this.a.style.width=u.round(100*this.c.bufferedPercent(),2)+"%")};u.Yb=u.b.extend({h:function(a,c){u.b.call(this,a,c)}});u.Yb.prototype.e=function(){return u.b.prototype.e.call(this,"div",{className:"vjs-play-progress",innerHTML:'<span class="vjs-control-text">Progress: 0%</span>'})};u.Ha=u.W.extend({h:function(a,c){u.W.call(this,a,c);a.d("timeupdate",u.bind(this,this.da))}});u.Ha.prototype.defaultValue="00:00";
u.Ha.prototype.e=function(){return u.W.prototype.e.call(this,"div",{className:"vjs-seek-handle","aria-live":"off"})};u.Ha.prototype.da=function(){var a=this.c.Va?this.c.u.currentTime:this.c.currentTime();this.a.innerHTML='<span class="vjs-control-text">'+u.ua(a,this.c.duration())+"</span>"};u.jb=u.b.extend({h:function(a,c){u.b.call(this,a,c);a.j&&(a.j.n&&a.j.n.volumeControl===l)&&this.m("vjs-hidden");a.d("loadstart",u.bind(this,function(){a.j.n&&a.j.n.volumeControl===l?this.m("vjs-hidden"):this.r("vjs-hidden")}))}});
u.jb.prototype.i={children:{volumeBar:{}}};u.jb.prototype.e=function(){return u.b.prototype.e.call(this,"div",{className:"vjs-volume-control vjs-control"})};u.ib=u.O.extend({h:function(a,c){u.O.call(this,a,c);a.d("volumechange",u.bind(this,this.Ba));a.L(u.bind(this,this.Ba))}});t=u.ib.prototype;t.Ba=function(){this.a.setAttribute("aria-valuenow",u.round(100*this.c.volume(),2));this.a.setAttribute("aria-valuetext",u.round(100*this.c.volume(),2)+"%")};
t.i={children:{volumeLevel:{},volumeHandle:{}},barName:"volumeLevel",handleName:"volumeHandle"};t.uc="volumechange";t.e=function(){return u.O.prototype.e.call(this,"div",{className:"vjs-volume-bar","aria-label":"volume level"})};t.Hb=function(a){this.c.muted()&&this.c.muted(l);this.c.volume(F(this,a))};t.yb=function(){return this.c.muted()?0:this.c.volume()};t.Bc=function(){this.c.volume(this.c.volume()+0.1)};t.Ac=function(){this.c.volume(this.c.volume()-0.1)};
u.ec=u.b.extend({h:function(a,c){u.b.call(this,a,c)}});u.ec.prototype.e=function(){return u.b.prototype.e.call(this,"div",{className:"vjs-volume-level",innerHTML:'<span class="vjs-control-text"></span>'})};u.kb=u.W.extend();u.kb.prototype.defaultValue="00:00";u.kb.prototype.e=function(){return u.W.prototype.e.call(this,"div",{className:"vjs-volume-handle"})};
u.ea=u.q.extend({h:function(a,c){u.q.call(this,a,c);a.d("volumechange",u.bind(this,this.update));a.j&&(a.j.n&&a.j.n.volumeControl===l)&&this.m("vjs-hidden");a.d("loadstart",u.bind(this,function(){a.j.n&&a.j.n.volumeControl===l?this.m("vjs-hidden"):this.r("vjs-hidden")}))}});u.ea.prototype.e=function(){return u.q.prototype.e.call(this,"div",{className:"vjs-mute-control vjs-control",innerHTML:'<div><span class="vjs-control-text">Mute</span></div>'})};
u.ea.prototype.p=function(){this.c.muted(this.c.muted()?l:f)};u.ea.prototype.update=function(){var a=this.c.volume(),c=3;0===a||this.c.muted()?c=0:0.33>a?c=1:0.67>a&&(c=2);this.c.muted()?"Unmute"!=this.a.children[0].children[0].innerHTML&&(this.a.children[0].children[0].innerHTML="Unmute"):"Mute"!=this.a.children[0].children[0].innerHTML&&(this.a.children[0].children[0].innerHTML="Mute");for(a=0;4>a;a++)u.r(this.a,"vjs-vol-"+a);u.m(this.a,"vjs-vol-"+c)};
u.na=u.S.extend({h:function(a,c){u.S.call(this,a,c);a.d("volumechange",u.bind(this,this.update));a.j&&(a.j.n&&a.j.n.Fc===l)&&this.m("vjs-hidden");a.d("loadstart",u.bind(this,function(){a.j.n&&a.j.n.Fc===l?this.m("vjs-hidden"):this.r("vjs-hidden")}));this.m("vjs-menu-button")}});u.na.prototype.Ma=function(){var a=new u.ma(this.c,{Wc:"div"}),c=new u.ib(this.c,u.l.B({Od:f},this.i.ge));a.Y(c);return a};u.na.prototype.p=function(){u.ea.prototype.p.call(this);u.S.prototype.p.call(this)};
u.na.prototype.e=function(){return u.q.prototype.e.call(this,"div",{className:"vjs-volume-menu-button vjs-menu-button vjs-control",innerHTML:'<div><span class="vjs-control-text">Mute</span></div>'})};u.na.prototype.update=u.ea.prototype.update;u.Ga=u.q.extend({h:function(a,c){u.q.call(this,a,c);a.poster()&&this.src(a.poster());(!a.poster()||!a.controls())&&this.F();a.d("posterchange",u.bind(this,function(){this.src(a.poster())}));a.d("play",u.bind(this,this.F))}});var R="backgroundSize"in u.G.style;
u.Ga.prototype.e=function(){var a=u.e("div",{className:"vjs-poster",tabIndex:-1});R||a.appendChild(u.e("img"));return a};u.Ga.prototype.src=function(a){var c=this.v();a!==b&&(R?c.style.backgroundImage='url("'+a+'")':c.firstChild.src=a)};u.Ga.prototype.p=function(){this.C().controls()&&this.c.play()};
u.Xb=u.b.extend({h:function(a,c){u.b.call(this,a,c);a.d("canplay",u.bind(this,this.F));a.d("canplaythrough",u.bind(this,this.F));a.d("playing",u.bind(this,this.F));a.d("seeking",u.bind(this,this.show));a.d("seeked",u.bind(this,this.F));a.d("error",u.bind(this,this.show));a.d("ended",u.bind(this,this.F));a.d("waiting",u.bind(this,this.show))}});u.Xb.prototype.e=function(){return u.b.prototype.e.call(this,"div",{className:"vjs-loading-spinner"})};u.Za=u.q.extend();
u.Za.prototype.e=function(){return u.q.prototype.e.call(this,"div",{className:"vjs-big-play-button",innerHTML:'<span aria-hidden="true"></span>',"aria-label":"play video"})};u.Za.prototype.p=function(){this.c.play()};
u.s=u.b.extend({h:function(a,c,d){c=c||{};c.xc=l;u.b.call(this,a,c,d);var e,g;g=this;e=this.C();a=function(){if(e.controls()&&!e.usingNativeControls()){var a;g.d("mousedown",g.p);g.d("touchstart",function(c){c.preventDefault();a=this.c.userActive()});g.d("touchmove",function(){a&&this.C().reportUserActivity()});var c,d,n,s;c=0;g.d("touchstart",function(){c=(new Date).getTime();n=f});s=function(){n=l};g.d("touchmove",s);g.d("touchleave",s);g.d("touchcancel",s);g.d("touchend",function(){n===f&&(d=(new Date).getTime()-
c,250>d&&this.k("tap"))});g.d("tap",g.ud)}};c=u.bind(g,g.Bd);this.L(a);e.d("controlsenabled",a);e.d("controlsdisabled",c)}});t=u.s.prototype;t.Bd=function(){this.o("tap");this.o("touchstart");this.o("touchmove");this.o("touchleave");this.o("touchcancel");this.o("touchend");this.o("click");this.o("mousedown")};t.p=function(a){0===a.button&&this.C().controls()&&(this.C().paused()?this.C().play():this.C().pause())};t.ud=function(){this.C().userActive(!this.C().userActive())};t.Mb=m();
t.n={volumeControl:f,fullscreenResize:l,progressEvents:l,timeupdateEvents:l};u.media={};u.media.Ya="play pause paused currentTime setCurrentTime duration buffered volume setVolume muted setMuted width height supportsFullScreen enterFullScreen src load currentSrc preload setPreload autoplay setAutoplay loop setLoop error networkState readyState seeking initialTime startOffsetTime played seekable ended videoTracks audioTracks videoWidth videoHeight textTracks defaultPlaybackRate playbackRate mediaGroup controller controls defaultMuted".split(" ");
function ea(){var a=u.media.Ya[i];return function(){throw Error('The "'+a+"\" method is not available on the playback technology's API");}}for(var i=u.media.Ya.length-1;0<=i;i--)u.s.prototype[u.media.Ya[i]]=ea();
u.g=u.s.extend({h:function(a,c,d){this.n.volumeControl=u.g.Vc();this.n.movingMediaElementInDOM=!u.Kc;this.n.fullscreenResize=f;u.s.call(this,a,c,d);for(d=u.g.cb.length-1;0<=d;d--)u.d(this.a,u.g.cb[d],u.bind(this.c,this.cd));(c=c.source)&&this.a.currentSrc===c.src&&0<this.a.networkState?a.k("loadstart"):c&&(this.a.src=c.src);if(u.bc&&a.options().nativeControlsForTouch!==l){var e,g,j,k;e=this;g=this.C();c=g.controls();e.a.controls=!!c;j=function(){e.a.controls=f};k=function(){e.a.controls=l};g.d("controlsenabled",
j);g.d("controlsdisabled",k);c=function(){g.o("controlsenabled",j);g.o("controlsdisabled",k)};e.d("dispose",c);g.d("usingcustomcontrols",c);g.usingNativeControls(f)}a.L(function(){this.M&&(this.i.autoplay&&this.paused())&&(delete this.M.poster,this.play())});this.Aa()}});t=u.g.prototype;t.dispose=function(){u.s.prototype.dispose.call(this)};
t.e=function(){var a=this.c,c=a.M,d;if(!c||this.n.movingMediaElementInDOM===l)c?(d=c.cloneNode(l),u.g.ic(c),c=d,a.M=h):c=u.e("video",{id:a.id()+"_html5_api",className:"vjs-tech"}),c.player=a,u.zb(c,a.v());d=["autoplay","preload","loop","muted"];for(var e=d.length-1;0<=e;e--){var g=d[e];a.i[g]!==h&&(c[g]=a.i[g])}return c};t.cd=function(a){this.k(a);a.stopPropagation()};t.play=function(){this.a.play()};t.pause=function(){this.a.pause()};t.paused=function(){return this.a.paused};t.currentTime=function(){return this.a.currentTime};
t.Dd=function(a){try{this.a.currentTime=a}catch(c){u.log(c,"Video is not ready. (Video.js)")}};t.duration=function(){return this.a.duration||0};t.buffered=function(){return this.a.buffered};t.volume=function(){return this.a.volume};t.Id=function(a){this.a.volume=a};t.muted=function(){return this.a.muted};t.Gd=function(a){this.a.muted=a};t.width=function(){return this.a.offsetWidth};t.height=function(){return this.a.offsetHeight};
t.Wa=function(){return"function"==typeof this.a.webkitEnterFullScreen&&(/Android/.test(u.I)||!/Chrome|Mac OS X 10.5/.test(u.I))?f:l};t.jc=function(){var a=this.a;a.paused&&a.networkState<=a.Sd?(this.a.play(),setTimeout(function(){a.pause();a.webkitEnterFullScreen()},0)):a.webkitEnterFullScreen()};t.dd=function(){this.a.webkitExitFullScreen()};t.src=function(a){this.a.src=a};t.load=function(){this.a.load()};t.currentSrc=function(){return this.a.currentSrc};t.poster=function(){return this.a.poster};
t.Mb=function(a){this.a.poster=a};t.Sa=function(){return this.a.Sa};t.Hd=function(a){this.a.Sa=a};t.autoplay=function(){return this.a.autoplay};t.Cd=function(a){this.a.autoplay=a};t.controls=function(){return this.a.controls};t.loop=function(){return this.a.loop};t.Fd=function(a){this.a.loop=a};t.error=function(){return this.a.error};t.seeking=function(){return this.a.seeking};t.ended=function(){return this.a.ended};u.g.isSupported=function(){try{u.G.volume=0.5}catch(a){return l}return!!u.G.canPlayType};
u.g.ob=function(a){try{return!!u.G.canPlayType(a.type)}catch(c){return""}};u.g.Vc=function(){var a=u.G.volume;u.G.volume=a/2+0.1;return a!==u.G.volume};var S,fa=/^application\/(?:x-|vnd\.apple\.)mpegurl/i,ga=/^video\/mp4/i;
u.g.tc=function(){4<=u.Rb&&(S||(S=u.G.constructor.prototype.canPlayType),u.G.constructor.prototype.canPlayType=function(a){return a&&fa.test(a)?"maybe":S.call(this,a)});u.Oc&&(S||(S=u.G.constructor.prototype.canPlayType),u.G.constructor.prototype.canPlayType=function(a){return a&&ga.test(a)?"maybe":S.call(this,a)})};u.g.Nd=function(){var a=u.G.constructor.prototype.canPlayType;u.G.constructor.prototype.canPlayType=S;S=h;return a};u.g.tc();u.g.cb="loadstart suspend abort error emptied stalled loadedmetadata loadeddata canplay canplaythrough playing waiting seeking seeked ended durationchange timeupdate progress play pause ratechange volumechange".split(" ");
u.g.ic=function(a){if(a){a.player=h;for(a.parentNode&&a.parentNode.removeChild(a);a.hasChildNodes();)a.removeChild(a.firstChild);a.removeAttribute("src");if("function"===typeof a.load)try{a.load()}catch(c){}}};
u.f=u.s.extend({h:function(a,c,d){u.s.call(this,a,c,d);var e=c.source;d=c.parentEl;var g=this.a=u.e("div",{id:a.id()+"_temp_flash"}),j=a.id()+"_flash_api";a=a.i;var k=u.l.B({readyFunction:"videojs.Flash.onReady",eventProxyFunction:"videojs.Flash.onEvent",errorEventProxyFunction:"videojs.Flash.onError",autoplay:a.autoplay,preload:a.Sa,loop:a.loop,muted:a.muted},c.flashVars),r=u.l.B({wmode:"opaque",bgcolor:"#000000"},c.params),n=u.l.B({id:j,name:j,"class":"vjs-tech"},c.attributes),s;e&&(e.type&&u.f.ld(e.type)?
(a=u.f.Cc(e.src),k.rtmpConnection=encodeURIComponent(a.rb),k.rtmpStream=encodeURIComponent(a.Nb)):k.src=encodeURIComponent(u.mc(e.src)));this.setCurrentTime=function(a){s=a;this.a.vjs_setProperty("currentTime",a)};this.currentTime=function(){return this.seeking()?s:this.a.vjs_getProperty("currentTime")};u.zb(g,d);c.startTime&&this.L(function(){this.load();this.play();this.currentTime(c.startTime)});u.Vb&&this.L(function(){u.d(this.v(),"mousemove",u.bind(this,function(){this.C().k({type:"mousemove",
bubbles:l})}))});if(c.iFrameMode===f&&!u.Vb){var D=u.e("iframe",{id:j+"_iframe",name:j+"_iframe",className:"vjs-tech",scrolling:"no",marginWidth:0,marginHeight:0,frameBorder:0});k.readyFunction="ready";k.eventProxyFunction="events";k.errorEventProxyFunction="errors";u.d(D,"load",u.bind(this,function(){var a,d=D.contentWindow;a=D.contentDocument?D.contentDocument:D.contentWindow.document;a.write(u.f.nc(c.swf,k,r,n));d.player=this.c;d.ready=u.bind(this.c,function(c){var d=this.j;d.a=a.getElementById(c);
u.f.qb(d)});d.events=u.bind(this.c,function(a,c){this&&"flash"===this.ya&&this.k(c)});d.errors=u.bind(this.c,function(a,c){u.log("Flash Error",c)})}));g.parentNode.replaceChild(D,g)}else u.f.bd(c.swf,g,k,r,n)}});t=u.f.prototype;t.dispose=function(){u.s.prototype.dispose.call(this)};t.play=function(){this.a.vjs_play()};t.pause=function(){this.a.vjs_pause()};
t.src=function(a){if(a===b)return this.currentSrc();u.f.kd(a)?(a=u.f.Cc(a),this.be(a.rb),this.ce(a.Nb)):(a=u.mc(a),this.a.vjs_src(a));if(this.c.autoplay()){var c=this;setTimeout(function(){c.play()},0)}};t.currentSrc=function(){var a=this.a.vjs_getProperty("currentSrc");if(a==h){var c=this.rtmpConnection(),d=this.rtmpStream();c&&d&&(a=u.f.Jd(c,d))}return a};t.load=function(){this.a.vjs_load()};t.poster=function(){this.a.vjs_getProperty("poster")};t.Mb=m();t.buffered=function(){return u.tb(0,this.a.vjs_getProperty("buffered"))};
t.Wa=q(l);t.jc=q(l);var T=u.f.prototype,U="rtmpConnection rtmpStream preload defaultPlaybackRate playbackRate autoplay loop mediaGroup controller controls volume muted defaultMuted".split(" "),V="error networkState readyState seeking initialTime duration startOffsetTime paused played seekable ended videoTracks audioTracks videoWidth videoHeight textTracks".split(" ");function ha(){var a=U[W],c=a.charAt(0).toUpperCase()+a.slice(1);T["set"+c]=function(c){return this.a.vjs_setProperty(a,c)}}
function X(a){T[a]=function(){return this.a.vjs_getProperty(a)}}var W;for(W=0;W<U.length;W++)X(U[W]),ha();for(W=0;W<V.length;W++)X(V[W]);u.f.isSupported=function(){return 10<=u.f.version()[0]};u.f.ob=function(a){if(!a.type)return"";a=a.type.replace(/;.*/,"").toLowerCase();if(a in u.f.fd||a in u.f.Dc)return"maybe"};u.f.fd={"video/flv":"FLV","video/x-flv":"FLV","video/mp4":"MP4","video/m4v":"MP4"};u.f.Dc={"rtmp/mp4":"MP4","rtmp/flv":"FLV"};
u.f.onReady=function(a){a=u.v(a);var c=a.player||a.parentNode.player,d=c.j;a.player=c;d.a=a;u.f.qb(d)};u.f.qb=function(a){a.v().vjs_getProperty?a.Aa():setTimeout(function(){u.f.qb(a)},50)};u.f.onEvent=function(a,c){u.v(a).player.k(c)};u.f.onError=function(a,c){u.v(a).player.k("error");u.log("Flash Error",c,a)};
u.f.version=function(){var a="0,0,0";try{a=(new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version").replace(/\D+/g,",").match(/^,?(.+),?$/)[1]}catch(c){try{navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin&&(a=(navigator.plugins["Shockwave Flash 2.0"]||navigator.plugins["Shockwave Flash"]).description.replace(/\D+/g,",").match(/^,?(.+),?$/)[1])}catch(d){}}return a.split(",")};
u.f.bd=function(a,c,d,e,g){a=u.f.nc(a,d,e,g);a=u.e("div",{innerHTML:a}).childNodes[0];d=c.parentNode;c.parentNode.replaceChild(a,c);var j=d.childNodes[0];setTimeout(function(){j.style.display="block"},1E3)};
u.f.nc=function(a,c,d,e){var g="",j="",k="";c&&u.l.sa(c,function(a,c){g+=a+"="+c+"&amp;"});d=u.l.B({movie:a,flashvars:g,allowScriptAccess:"always",allowNetworking:"all"},d);u.l.sa(d,function(a,c){j+='<param name="'+a+'" value="'+c+'" />'});e=u.l.B({data:a,width:"100%",height:"100%"},e);u.l.sa(e,function(a,c){k+=a+'="'+c+'" '});return'<object type="application/x-shockwave-flash"'+k+">"+j+"</object>"};u.f.Jd=function(a,c){return a+"&"+c};
u.f.Cc=function(a){var c={rb:"",Nb:""};if(!a)return c;var d=a.indexOf("&"),e;-1!==d?e=d+1:(d=e=a.lastIndexOf("/")+1,0===d&&(d=e=a.length));c.rb=a.substring(0,d);c.Nb=a.substring(e,a.length);return c};u.f.ld=function(a){return a in u.f.Dc};u.f.Qc=/^rtmp[set]?:\/\//i;u.f.kd=function(a){return u.f.Qc.test(a)};
u.Pc=u.b.extend({h:function(a,c,d){u.b.call(this,a,c,d);if(!a.i.sources||0===a.i.sources.length){c=0;for(d=a.i.techOrder;c<d.length;c++){var e=u.Z(d[c]),g=window.videojs[e];if(g&&g.isSupported()){I(a,e);break}}}else a.src(a.i.sources)}});u.Player.prototype.textTracks=function(){return this.za=this.za||[]};function Y(a,c,d){for(var e=a.za,g=0,j=e.length,k,r;g<j;g++)k=e[g],k.id()===c?(k.show(),r=k):d&&(k.H()==d&&0<k.mode())&&k.disable();(c=r?r.H():d?d:l)&&a.k(c+"trackchange")}
u.w=u.b.extend({h:function(a,c){u.b.call(this,a,c);this.R=c.id||"vjs_"+c.kind+"_"+c.language+"_"+u.t++;this.zc=c.src;this.Zc=c["default"]||c.dflt;this.Ld=c.title;this.Zd=c.srclang;this.md=c.label;this.$=[];this.lb=[];this.ha=this.ia=0;this.c.d("fullscreenchange",u.bind(this,this.Sc))}});t=u.w.prototype;t.H=p("A");t.src=p("zc");t.ub=p("Zc");t.title=p("Ld");t.label=p("md");t.Xc=p("$");t.Rc=p("lb");t.readyState=p("ia");t.mode=p("ha");
t.Sc=function(){this.a.style.fontSize=this.c.isFullScreen()?140*(screen.width/this.c.width())+"%":""};t.e=function(){return u.b.prototype.e.call(this,"div",{className:"vjs-"+this.A+" vjs-text-track"})};t.show=function(){ia(this);this.ha=2;u.b.prototype.show.call(this)};t.F=function(){ia(this);this.ha=1;u.b.prototype.F.call(this)};
t.disable=function(){2==this.ha&&this.F();this.c.o("timeupdate",u.bind(this,this.update,this.R));this.c.o("ended",u.bind(this,this.reset,this.R));this.reset();this.c.ga("textTrackDisplay").removeChild(this);this.ha=0};function ia(a){0===a.ia&&a.load();0===a.ha&&(a.c.d("timeupdate",u.bind(a,a.update,a.R)),a.c.d("ended",u.bind(a,a.reset,a.R)),("captions"===a.A||"subtitles"===a.A)&&a.c.ga("textTrackDisplay").Y(a))}
t.load=function(){0===this.ia&&(this.ia=1,u.get(this.zc,u.bind(this,this.zd),u.bind(this,this.Gb)))};t.Gb=function(a){this.error=a;this.ia=3;this.k("error")};t.zd=function(a){var c,d;a=a.split("\n");for(var e="",g=1,j=a.length;g<j;g++)if(e=u.trim(a[g])){-1==e.indexOf("--\x3e")?(c=e,e=u.trim(a[++g])):c=this.$.length;c={id:c,index:this.$.length};d=e.split(" --\x3e ");c.startTime=ja(d[0]);c.ta=ja(d[1]);for(d=[];a[++g]&&(e=u.trim(a[g]));)d.push(e);c.text=d.join("<br/>");this.$.push(c)}this.ia=2;this.k("loaded")};
function ja(a){var c=a.split(":");a=0;var d,e,g;3==c.length?(d=c[0],e=c[1],c=c[2]):(d=0,e=c[0],c=c[1]);c=c.split(/\s+/);c=c.splice(0,1)[0];c=c.split(/\.|,/);g=parseFloat(c[1]);c=c[0];a+=3600*parseFloat(d);a+=60*parseFloat(e);a+=parseFloat(c);g&&(a+=g/1E3);return a}
t.update=function(){if(0<this.$.length){var a=this.c.currentTime();if(this.Lb===b||a<this.Lb||this.Oa<=a){var c=this.$,d=this.c.duration(),e=0,g=l,j=[],k,r,n,s;a>=this.Oa||this.Oa===b?s=this.wb!==b?this.wb:0:(g=f,s=this.Cb!==b?this.Cb:c.length-1);for(;;){n=c[s];if(n.ta<=a)e=Math.max(e,n.ta),n.Ja&&(n.Ja=l);else if(a<n.startTime){if(d=Math.min(d,n.startTime),n.Ja&&(n.Ja=l),!g)break}else g?(j.splice(0,0,n),r===b&&(r=s),k=s):(j.push(n),k===b&&(k=s),r=s),d=Math.min(d,n.ta),e=Math.max(e,n.startTime),n.Ja=
f;if(g)if(0===s)break;else s--;else if(s===c.length-1)break;else s++}this.lb=j;this.Oa=d;this.Lb=e;this.wb=k;this.Cb=r;a=this.lb;c="";d=0;for(e=a.length;d<e;d++)c+='<span class="vjs-tt-cue">'+a[d].text+"</span>";this.a.innerHTML=c;this.k("cuechange")}}};t.reset=function(){this.Oa=0;this.Lb=this.c.duration();this.Cb=this.wb=0};u.Tb=u.w.extend();u.Tb.prototype.A="captions";u.ac=u.w.extend();u.ac.prototype.A="subtitles";u.Ub=u.w.extend();u.Ub.prototype.A="chapters";
u.cc=u.b.extend({h:function(a,c,d){u.b.call(this,a,c,d);if(a.i.tracks&&0<a.i.tracks.length){c=this.c;a=a.i.tracks;var e;for(d=0;d<a.length;d++){e=a[d];var g=c,j=e.kind,k=e.label,r=e.language,n=e;e=g.za=g.za||[];n=n||{};n.kind=j;n.label=k;n.language=r;j=u.Z(j||"subtitles");g=new window.videojs[j+"Track"](g,n);e.push(g)}}}});u.cc.prototype.e=function(){return u.b.prototype.e.call(this,"div",{className:"vjs-text-track-display"})};
u.X=u.N.extend({h:function(a,c){var d=this.ca=c.track;c.label=d.label();c.selected=d.ub();u.N.call(this,a,c);this.c.d(d.H()+"trackchange",u.bind(this,this.update))}});u.X.prototype.p=function(){u.N.prototype.p.call(this);Y(this.c,this.ca.R,this.ca.H())};u.X.prototype.update=function(){this.selected(2==this.ca.mode())};u.fb=u.X.extend({h:function(a,c){c.track={H:function(){return c.kind},C:a,label:function(){return c.kind+" off"},ub:q(l),mode:q(l)};u.X.call(this,a,c);this.selected(f)}});
u.fb.prototype.p=function(){u.X.prototype.p.call(this);Y(this.c,this.ca.R,this.ca.H())};u.fb.prototype.update=function(){for(var a=this.c.textTracks(),c=0,d=a.length,e,g=f;c<d;c++)e=a[c],e.H()==this.ca.H()&&2==e.mode()&&(g=l);this.selected(g)};u.T=u.S.extend({h:function(a,c){u.S.call(this,a,c);1>=this.K.length&&this.F()}});
u.T.prototype.ra=function(){var a=[],c;a.push(new u.fb(this.c,{kind:this.A}));for(var d=0;d<this.c.textTracks().length;d++)c=this.c.textTracks()[d],c.H()===this.A&&a.push(new u.X(this.c,{track:c}));return a};u.Ca=u.T.extend({h:function(a,c,d){u.T.call(this,a,c,d);this.a.setAttribute("aria-label","Captions Menu")}});u.Ca.prototype.A="captions";u.Ca.prototype.pa="Captions";u.Ca.prototype.className="vjs-captions-button";
u.Ia=u.T.extend({h:function(a,c,d){u.T.call(this,a,c,d);this.a.setAttribute("aria-label","Subtitles Menu")}});u.Ia.prototype.A="subtitles";u.Ia.prototype.pa="Subtitles";u.Ia.prototype.className="vjs-subtitles-button";u.Da=u.T.extend({h:function(a,c,d){u.T.call(this,a,c,d);this.a.setAttribute("aria-label","Chapters Menu")}});t=u.Da.prototype;t.A="chapters";t.pa="Chapters";t.className="vjs-chapters-button";
t.ra=function(){for(var a=[],c,d=0;d<this.c.textTracks().length;d++)c=this.c.textTracks()[d],c.H()===this.A&&a.push(new u.X(this.c,{track:c}));return a};
t.Ma=function(){for(var a=this.c.textTracks(),c=0,d=a.length,e,g,j=this.K=[];c<d;c++)if(e=a[c],e.H()==this.A&&e.ub()){if(2>e.readyState()){this.Wd=e;e.d("loaded",u.bind(this,this.Ma));return}g=e;break}a=this.va=new u.ma(this.c);a.fa().appendChild(u.e("li",{className:"vjs-menu-title",innerHTML:u.Z(this.A),Kd:-1}));if(g){e=g.$;for(var k,c=0,d=e.length;c<d;c++)k=e[c],k=new u.$a(this.c,{track:g,cue:k}),j.push(k),a.Y(k)}0<this.K.length&&this.show();return a};
u.$a=u.N.extend({h:function(a,c){var d=this.ca=c.track,e=this.cue=c.cue,g=a.currentTime();c.label=e.text;c.selected=e.startTime<=g&&g<e.ta;u.N.call(this,a,c);d.d("cuechange",u.bind(this,this.update))}});u.$a.prototype.p=function(){u.N.prototype.p.call(this);this.c.currentTime(this.cue.startTime);this.update(this.cue.startTime)};u.$a.prototype.update=function(){var a=this.cue,c=this.c.currentTime();this.selected(a.startTime<=c&&c<a.ta)};
u.l.B(u.Ea.prototype.i.children,{subtitlesButton:{},captionsButton:{},chaptersButton:{}});
if("undefined"!==typeof window.JSON&&"function"===window.JSON.parse)u.JSON=window.JSON;else{u.JSON={};var Z=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g;u.JSON.parse=function(a,c){function d(a,e){var k,r,n=a[e];if(n&&"object"===typeof n)for(k in n)Object.prototype.hasOwnProperty.call(n,k)&&(r=d(n,k),r!==b?n[k]=r:delete n[k]);return c.call(a,e,n)}var e;a=String(a);Z.lastIndex=0;Z.test(a)&&(a=a.replace(Z,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));
if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return e=eval("("+a+")"),"function"===typeof c?d({"":e},""):e;throw new SyntaxError("JSON.parse(): invalid or malformed JSON data");}}
u.fc=function(){var a,c,d=document.getElementsByTagName("video");if(d&&0<d.length)for(var e=0,g=d.length;e<g;e++)if((c=d[e])&&c.getAttribute)c.player===b&&(a=c.getAttribute("data-setup"),a!==h&&(a=u.JSON.parse(a||"{}"),videojs(c,a)));else{u.mb();break}else u.Gc||u.mb()};u.mb=function(){setTimeout(u.fc,1)};"complete"===document.readyState?u.Gc=f:u.U(window,"load",function(){u.Gc=f});u.mb();u.Ad=function(a,c){u.Player.prototype[a]=c};var ka=this;ka.Rd=f;function $(a,c){var d=a.split("."),e=ka;!(d[0]in e)&&e.execScript&&e.execScript("var "+d[0]);for(var g;d.length&&(g=d.shift());)!d.length&&c!==b?e[g]=c:e=e[g]?e[g]:e[g]={}};$("videojs",u);$("_V_",u);$("videojs.options",u.options);$("videojs.players",u.wa);$("videojs.TOUCH_ENABLED",u.bc);$("videojs.cache",u.qa);$("videojs.Component",u.b);u.b.prototype.player=u.b.prototype.C;u.b.prototype.options=u.b.prototype.options;u.b.prototype.init=u.b.prototype.h;u.b.prototype.dispose=u.b.prototype.dispose;u.b.prototype.createEl=u.b.prototype.e;u.b.prototype.contentEl=u.b.prototype.fa;u.b.prototype.el=u.b.prototype.v;u.b.prototype.addChild=u.b.prototype.Y;
u.b.prototype.getChild=u.b.prototype.ga;u.b.prototype.getChildById=u.b.prototype.gd;u.b.prototype.children=u.b.prototype.children;u.b.prototype.initChildren=u.b.prototype.pc;u.b.prototype.removeChild=u.b.prototype.removeChild;u.b.prototype.on=u.b.prototype.d;u.b.prototype.off=u.b.prototype.o;u.b.prototype.one=u.b.prototype.U;u.b.prototype.trigger=u.b.prototype.k;u.b.prototype.triggerReady=u.b.prototype.Aa;u.b.prototype.show=u.b.prototype.show;u.b.prototype.hide=u.b.prototype.F;
u.b.prototype.width=u.b.prototype.width;u.b.prototype.height=u.b.prototype.height;u.b.prototype.dimensions=u.b.prototype.$c;u.b.prototype.ready=u.b.prototype.L;u.b.prototype.addClass=u.b.prototype.m;u.b.prototype.removeClass=u.b.prototype.r;u.b.prototype.buildCSSClass=u.b.prototype.Q;u.Player.prototype.ended=u.Player.prototype.ended;$("videojs.MediaLoader",u.Pc);$("videojs.TextTrackDisplay",u.cc);$("videojs.ControlBar",u.Ea);$("videojs.Button",u.q);$("videojs.PlayToggle",u.Zb);
$("videojs.FullscreenToggle",u.Fa);$("videojs.BigPlayButton",u.Za);$("videojs.LoadingSpinner",u.Xb);$("videojs.CurrentTimeDisplay",u.ab);$("videojs.DurationDisplay",u.bb);$("videojs.TimeDivider",u.dc);$("videojs.RemainingTimeDisplay",u.hb);$("videojs.LiveDisplay",u.Wb);$("videojs.Slider",u.O);$("videojs.ProgressControl",u.gb);$("videojs.SeekBar",u.$b);$("videojs.LoadProgressBar",u.eb);$("videojs.PlayProgressBar",u.Yb);$("videojs.SeekHandle",u.Ha);$("videojs.VolumeControl",u.jb);
$("videojs.VolumeBar",u.ib);$("videojs.VolumeLevel",u.ec);$("videojs.VolumeMenuButton",u.na);$("videojs.VolumeHandle",u.kb);$("videojs.MuteToggle",u.ea);$("videojs.PosterImage",u.Ga);$("videojs.Menu",u.ma);$("videojs.MenuItem",u.N);$("videojs.MenuButton",u.S);u.S.prototype.createItems=u.S.prototype.ra;u.T.prototype.createItems=u.T.prototype.ra;u.Da.prototype.createItems=u.Da.prototype.ra;$("videojs.SubtitlesButton",u.Ia);$("videojs.CaptionsButton",u.Ca);$("videojs.ChaptersButton",u.Da);
$("videojs.MediaTechController",u.s);u.s.prototype.features=u.s.prototype.n;u.s.prototype.n.volumeControl=u.s.prototype.n.Fc;u.s.prototype.n.fullscreenResize=u.s.prototype.n.Xd;u.s.prototype.n.progressEvents=u.s.prototype.n.ae;u.s.prototype.n.timeupdateEvents=u.s.prototype.n.de;u.s.prototype.setPoster=u.s.prototype.Mb;$("videojs.Html5",u.g);u.g.Events=u.g.cb;u.g.isSupported=u.g.isSupported;u.g.canPlaySource=u.g.ob;u.g.patchCanPlayType=u.g.tc;u.g.unpatchCanPlayType=u.g.Nd;
u.g.prototype.setCurrentTime=u.g.prototype.Dd;u.g.prototype.setVolume=u.g.prototype.Id;u.g.prototype.setMuted=u.g.prototype.Gd;u.g.prototype.setPreload=u.g.prototype.Hd;u.g.prototype.setAutoplay=u.g.prototype.Cd;u.g.prototype.setLoop=u.g.prototype.Fd;u.g.prototype.enterFullScreen=u.g.prototype.jc;u.g.prototype.exitFullScreen=u.g.prototype.dd;$("videojs.Flash",u.f);u.f.isSupported=u.f.isSupported;u.f.canPlaySource=u.f.ob;u.f.onReady=u.f.onReady;$("videojs.TextTrack",u.w);u.w.prototype.label=u.w.prototype.label;
u.w.prototype.kind=u.w.prototype.H;u.w.prototype.mode=u.w.prototype.mode;u.w.prototype.cues=u.w.prototype.Xc;u.w.prototype.activeCues=u.w.prototype.Rc;$("videojs.CaptionsTrack",u.Tb);$("videojs.SubtitlesTrack",u.ac);$("videojs.ChaptersTrack",u.Ub);$("videojs.autoSetup",u.fc);$("videojs.plugin",u.Ad);$("videojs.createTimeRange",u.tb);$("videojs.util",u.ka);u.ka.mergeOptions=u.ka.Fb;})();
